wso2-extensions/identity-inbound-provisioning-scim2

.github/PULL_REQUEST_TEMPLATE.md

this is the pull-request-template for identity-inbound-provisioning-scim2 repo

introducing pull-request-template

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java

[List all changes you want to add here. If you fixed an issue, please
add a reference to that issue as well.]
-
[Please describe any preconditions that need to be addressed before we
can merge this pull request.]
[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]
-

removing SCIM2 user active state check

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java

Fixed scim resources' location urls
-
Immediately
None
-

IDENTITY-6402: Fix for invalid location urls of scim 2 resources

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java

- Code quality improvements
Immediately
None

Fixing some minor code issues

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config

- Enable user creation with askPassword and verifyEmail using SCIM 2.0
- https://wso2.org/jira/browse/IDENTITY-6326
- Immediately
- N/A

IDENTITY-6326: Enable user creation with askPassword and verifyEmail using SCIM 2.0

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.provider/pom.xml
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/BulkResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/GroupResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/MeResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/RecourceTypeResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/ServiceProviderConfigResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
features/org.wso2.carbon.identity.scim2.common.feature/pom.xml
features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml
features/org.wso2.carbon.identity.scim2.server.feature/pom.xml
pom.xml

- Fixing authorization header check
Immediately
N/A

Remove checking authorization header

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/AbstractResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/BulkResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/GroupResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/MeResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/RecourceTypeResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/ServiceProviderConfigResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/util/SupportUtils.java

- Adding support to extract username from CarbonContext thread-local instead of Authorization header to support protecting /Me endpoint with OAuth2
[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]
-

IDENTITY-6554: Extract username from threadLocal instead of Authorization Header

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMConfigProcessorTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/resources/charon-config-test.xml
components/org.wso2.carbon.identity.scim2.common/src/test/resources/testng.xml

Created SCIMCnfigProcessorTest commit #001

SCIMConfigProcessorTest#001

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManagerTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/resources/testng.xml

Created two test methods in IdentitySCIMManagerTest

IdentitySCIMManagerTest#001

---

components/org.wso2.carbon.identity.scim2.provider/pom.xml
components/org.wso2.carbon.identity.scim2.provider/src/main/webapp/WEB-INF/web.xml
pom.xml

Hide service listing in SCIM2 and upgrade cxf version

Hide service listing and upgrade cxf version

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java

Support pagination and CO,SW,EW Operations in SCIM user filtering with group names

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix issue in Application roles creation and filtering through SCIM
Resolves https://github.com/wso2/product-is/issues/3431

Fix issue in Application roles creation and filtering through SCIM

---

scim2.yaml

Adding .yaml file for the current SCIM2 APIs.

Adding yaml file for SCIM2 APIs 

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fixes https://github.com/wso2/product-is/issues/3679

scim2 filter from displayName is not working for the admin role

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

This PR is to fix https://github.com/wso2/product-is/issues/3748

Fix users can be deleted by the SCIM 2 'Delete User' service without enabling the SCIM

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
pom.xml

Fix http response of SCIM create user when the password/username policy mismatch
Fix wso2/product-is#4145

Fix http response of SCIM create/update user when the password/username policy mismatch

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Fixes [wso2/product-is#4388](https://github.com/wso2/product-is/issues/4388)
In listUsersWithGET method, we get the list of users as follows
`String[] userNames = carbonUM.getUserList(SCIMConstants.CommonSchemaConstants.ID_URI, "*", null);`
Then we invoke getSCIMUser method on all users.
```
private User getSCIMUser(String userName, List<String> claimURIList) throws CharonException {
User scimUser = null;
String userStoreDomainName = IdentityUtil.extractDomainFromName(userName);
if(StringUtils.isNotBlank(userStoreDomainName) && !isSCIMEnabled(userStoreDomainName)){
throw new CharonException("Cannot get user through scim to user store " + ". SCIM is not " +
"enabled for user store " + userStoreDomainName);
}
```
In case, SCIM is disabled for a particular userstore it will throw a …

Fix enabling SCIM only for specific user stores resulting in internal server error

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtil.java

Resolves https://github.com/wso2/product-is/issues/4401

Fix incorrect time on account creation

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Fix SCIM2 lists admin in full list, but not when specifically requested

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fixes https://github.com/wso2/product-is/issues/4388

Fix enabling SCIM only for specific user stores resulting in internal server error with Groups endpoint

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix #4285:Returns 500 If invalid password is provided when creating a user in SCIM2

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix #4688:Updating a Group throgh SCIM2 gives a unmatching action log in the carbon console

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

If exist, added primary user store domain to username in response

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

- Resolves [wso2_product_is#4980](https://github.com/wso2/product-is/issues/4980)
- Changed: validate both the offset and the limit at the same time
[Please describe any preconditions that need to be addressed before we
can merge this pull request.]
[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]
-

FIX pagination with limit equal to zero and count larger than 1 does not work properly in SCIM2 single attribute.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

- Resolves [wso2_product_is#4944](https://github.com/wso2/product-is/issues/4944)
- To handle the offset(startIndex) and limit(count) a separate method has been written.
- If the number of users returned from the filter is zero, then the same filter was used with offset as 1 and limit as the original offset to get matches till the original offset. Using that value, a new offset value was calculated. 
- If the number of users returned from the filter is not null (not zero), the new count (limit) count is calculated.
[Please describe any preconditions that need to be addressed before we
can merge this pull request.]
[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]
-

FIX Pagination when filtering through multiple domains using new APIs

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Regarding [wso2_product_is#4944](https://github.com/wso2/product-is/issues/4944)
- Fixing domain parameter in condition generation and offset calculation.

FIX domain parameter in condition generation.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Both the filtering scenario and listing users scenario uses the same logic to retrieve users. Therefore a common method is introduced.

Introducing a new function to be used for the filtering scenario and listing users scenario.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
pom.xml

Fix [wso2/product-is#4601](https://github.com/wso2/product-is/issues/4601)
Fix [wso2/product-is#4604](https://github.com/wso2/product-is/issues/4604)

Fix pagination in SCIM2 listUsers

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves: [wso2_product_is#5087](https://github.com/wso2/product-is/issues/5087)
Resolves: [wso2_product_is#5082](https://github.com/wso2/product-is/issues/5082)

FIX 'EW' operator used with domain is not working in SCIM2 single attribute filtering

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Get the user details from the userstore and send back the response for user creation. By doing this we could make scim get response and user creation response to be ideal.

Change user creation reponse

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/GroupDAO.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java

Fix [wso2/product-is #4961](https://github.com/wso2/product-is/issues/4961)

Fix SCIMCommonUtils.isFilteringEnhancementsEnabled() property is used in both request flow and response flow for two different behaviours

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Fix test fail in groups endpoint.

Fix filtering tests in groups endpoint.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolve [wso2_product_is#5204](https://github.com/wso2/product-is/issues/5204)

FIX validating filter operations in user endpoint.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Resolves [wso2_product_is#5213](https://github.com/wso2/product-is/issues/5213)

[FIX] Error when creating search value for CO, EW operators

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Error when patching SCIM 2 user resolved

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java

Resolves https://github.com/wso2/product-is/issues/5766

Fix extra comma

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix for Slowness in Group Patch Operation of SCIM2 API

---

features/org.wso2.carbon.identity.scim2.common.feature/pom.xml
features/org.wso2.carbon.identity.scim2.common.feature/resources/charon-config.xml.j2
features/org.wso2.carbon.identity.scim2.common.feature/resources/org.wso2.carbon.identity.scim2.common.feature.default.json
features/org.wso2.carbon.identity.scim2.common.feature/resources/org.wso2.carbon.identity.scim2.common.feature.infer.json
features/org.wso2.carbon.identity.scim2.common.feature/resources/p2.inf

**Proposed Changes**
- Add `charon-config.xml.j2` template.
- Add the relevant keys to the `default.json` and `infer.json` files.

Add charon-config.xml.j2 template.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandler.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandlerTest.java
pom.xml

Resolves wso2/product-is#5301, wso2/product-is#5328 and wso2/product-is#5540
Dependant on https://github.com/wso2/charon/pull/238

Include "location" & "$ref" attribute in SCIM2 responses

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java

Fix NPE in scim2 group listing

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

> Fixes https://github.com/wso2/product-is/issues/6004.
> - During the user update event, the existing user update method will be invoked. The contract of this method is that it will receive the new state of the user and that user will be updated in the database. Therefore this method is used for both SCIM PATCH and PUT operations to update the new user.
> - The internal implementation of the update user method first delete the existing user claims. Then it will add the new user claims. However, deleting all the user claims can lead to unexpected behaviors. One such example is deleting claims mapped to mandatory attributes(refer to https://github.com/wso2/product-is/issues/6004).
> - Therefore the _**update user claims**_ behavior is changed to add, delete or modify only the required …

[Public] Update User Claims Without Deleting Redundant User Claims

---

pom.xml

Upgrade Charon Version to 3.1.33

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
pom.xml

**Proposed changes in this pull request**
- Remove carbon.logging,commons-logging and log4j dependency.
- Add pax-logging dependency
- Remove maven-scr plugin
- Update dependency
**When to merge this PR**
- After identity-framework is updated with log4j2 changes.
- Need to upgrade framework version.

Migrate log4j2 update. 

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

related to https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/112
improved fix https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/179

Improved the Doc comments

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

This PR is to fix the `testListGroupsWithFilter` test in SCIM.

Fix a test

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves https://github.com/wso2/product-is/issues/6114

Fix the password policy error code

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/GroupDAO.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandler.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Add improvement to SCIM metadata generation for hybrid roles

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves : wso2/product-is#6621

Fix location URL is wrong when listing all users (Master)

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java

This PR resolves wso2/product-is#6627

Fix primary email ID not returned in SCIM user creation.

---

.gitignore
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java

Resolves https://github.com/wso2/product-is/issues/5209

Fix multi-valued attribute return type issue

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix for the Issue With List Group With Members when the members are not belongs to the specified user-store in the IS

---

features/org.wso2.carbon.identity.scim2.common.feature/resources/charon-config.xml.j2

**Proposed changes in this pull request**
Fix comments in the PR[1]
[1] - wso2/product-is#5801

Fix comments.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fixing comments in https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/142

Addressing requested changes

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix updating identity claims from SCIM while having a read only userstore

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtil.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManagerTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListenerTest.java
pom.xml

> Fixes https://github.com/wso2/product-is/issues/7123.

Change the implementation to use the user core unique id

---

pom.xml

Bump Charon Version

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix https://github.com/wso2/product-is/issues/7138

Include internal roles to the group

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/GroupResource.java
pom.xml

* Performance degradation in the SCIM Group Patch Add operation when the number of members in a group increases. Fixes https://github.com/wso2/product-is/issues/6918
* Preserve backward compatibility in Group Patch Add operation. Fixes https://github.com/wso2/product-is/issues/7143

Improve Group PATCH operation

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Improvement for https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/228
Refer https://github.com/wso2/product-is/issues/7138

Include internal roles to the users' group response

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/AbstractResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/util/SCIMProviderConstants.java

Resolves - wso2/product-is#6996

Validate charset param in request header

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves https://github.com/wso2/product-is/issues/7396
Partly Resolves https://github.com/wso2/product-is/issues/7339

Use userId for user attribute and role matching

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix https://github.com/wso2/product-is/issues/7399

Fix issue in SCIM2 multi attribute search

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListenerTest.java
pom.xml

Fix  https://github.com/wso2/product-is/issues/7300  and
https://github.com/wso2/product-is/issues/7425

Fix SCIM get request issue on invalid userid

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Resolves https://github.com/wso2/product-is/issues/7456

Change user listing method for scim2 getMe

---

pom.xml

Bump the wso2-charon version which fixes the https://github.com/wso2/product-is/issues/7520

Bump wso2-charon version

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
scim2.yaml

https://github.com/wso2/product-is/issues/7661

Fix issue by changing the response from internal server error to bad request

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

> Fixes https://github.com/wso2/product-is/issues/7663.
When a partial domain name is provided in the filter attribute value, that needs to be handled properly as it yields a Bad Request error. This PR validates any provided user-store domain in the filter attribute value.

Fix handling user-store domain while group filtering

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java

Resolves https://github.com/wso2/product-is/issues/7398

Remove redundant claim checks in doPostAddUserWithID()

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves https://github.com/wso2/product-is/issues/7383

Revert behavioural changes

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Related https://github.com/wso2/product-is/issues/7016

Remove meta claims when updating a user

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves https://github.com/wso2/product-is/issues/6053

Remove unnecessary logs

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java

Resolves https://github.com/wso2/product-is/issues/6053

Change unnecessary info logs to debug logs

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix for issue https://github.com/wso2/product-is/issues/7744

Handling inconsistency when updating a user password via SCIM2 REST API

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.provider/pom.xml
features/org.wso2.carbon.identity.scim2.common.feature/pom.xml
features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml
features/org.wso2.carbon.identity.scim2.server.feature/pom.xml
pom.xml

Upgrade Carbon Kernel version

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Since the username claim is immutable in the IS we will throw a bad request exception as per the SCIM2 specification.
> immutable  If one or more values are already set for the attribute,
the input value(s) MUST match, or HTTP status code 400 SHOULD be
returned with a "scimType" error code of "mutability".  If the
service provider has no existing values, the new value(s) SHALL be
applied.
https://tools.ietf.org/html/rfc7644#section-3.5.1
Resolves https://github.com/wso2/product-is/issues/8017

Throw bad request exception when trying to update username

---

.gitignore
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java

Fix code review comments for #211

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Return detailed error message for password history violation

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/IdentityResourceURLBuilder.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java
pom.xml

Related to wso2/product-is#8404
Depends on https://github.com/wso2/charon/pull/285

Build SCIM2 endpoint URLs and resolve tenant domain for tenant context mode

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fixes [product-is#8589](https://github.com/wso2/product-is/issues/8589)

fix group add 500 error

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponent.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponentHolder.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
components/org.wso2.carbon.identity.scim2.provider/pom.xml
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/RoleResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/webapp/WEB-INF/cxf-servlet.xml
pom.xml
scim2.yaml

Resolves wso2/product-is#8591
Depends on https://github.com/wso2/charon/pull/287, https://github.com/wso2/carbon-identity-framework/pull/3021, https://github.com/wso2/carbon-identity-framework/pull/3022

Add role management API

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java

Relates to wso2/product-is#8591

Fix group location value

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
pom.xml

Resolves wso2/product-is#9178
Depends on https://github.com/wso2/charon/pull/288

Add role and group separation changes to users and groups endpoints

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java

Change override method of "doPostGetUserClaimValues" to "doPostGetUserClaimValuesWithID" in SCIMUserOperationListener class.
**Related PR**: https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/273

Change override method of SCIMUserOperationListener class

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Resolves https://github.com/wso2/product-is/issues/6641
Requires https://github.com/wso2-support/identity-carbon-auth-rest/pull/51

Improve to honour service provider provisioning config

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
scim2.yaml

Related to https://github.com/wso2/product-is/issues/9041

Add backward compatibility changes

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Filtering SCIM groups when role belongs to Internal domain fails

---

pom.xml

Issue: https://github.com/wso2/product-is/issues/8005
Ran IS integration tests locally.

Upgrade CXF to 3.3.7

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/BulkResource.java
pom.xml

Depends on https://github.com/wso2/charon/pull/290
Resolves wso2/product-is#9233

Provide Roles support in SCIM2 /Bulk endpoint

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtil.java
pom.xml

Depends on https://github.com/wso2/carbon-kernel/pull/2778
Relates to https://github.com/wso2/product-is/issues/9040

Adding SCIM attributes for admin group

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtil.java

Resolves https://github.com/wso2/product-is/issues/9661

Fix admin group SCIM attributes creation

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
pom.xml

Fix for wso2/product-is#8135
Public fix of https://github.com/wso2-support/identity-inbound-provisioning-scim2/pull/94
Depends on https://github.com/wso2/carbon-kernel/pull/2705/
https://github.com/wso2/charon/pull/286

Update multi-valued claims separately in SCIM user

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Part of the fix for https://github.com/wso2/product-is/issues/7408

Improve client exception handling

---

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config

Part of the fix for https://github.com/wso2/product-is/issues/10020

Add forcePasswordReset and oneTimePassword claims

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves https://github.com/wso2/product-is/issues/10125
Fixes the error when building the search attribute value.

Fix filtering with CO or EW operations

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

To properly log user store exceptions.
**Resolves:** https://github.com/wso2/product-is/issues/9507

Log userstore exceptions

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
pom.xml

> Public fix for https://github.com/wso2/product-is/issues/9361
> https://github.com/wso2/carbon-kernel/pull/2804

Add error code 400 when username is empty in user creation

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java

> Resolves https://github.com/wso2/product-is/issues/10103

Update permissions method added for updating roles.

---

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config

Resolves https://github.com/wso2/product-is/issues/10434

Add country to scim2 extension schema claims

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManagerTest.java

* Resolved formatting issue reported in https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/89.

Resolved formatting issues in scim manager test cases

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java

Resolves https://github.com/wso2/product-is/issues/10424

Check whether role permissions have changed before updating

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
pom.xml

Improvements to SCIM group PATCH Operation performance

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

> Resolves https://github.com/wso2/product-is/issues/10444

Internal/everyone role skip removed when listing roles.

---

pom.xml

Charon version bumped

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

This fix is to skip retrieving users list for a role when the SCIM GET Group request is called with `attributes` or `excludedAttributes` query parameter, and the requested attributes do not contain `members` attribute or any sub attribute of `members`.
Related to improvement 1 described in https://github.com/wso2/product-is/issues/10581

Skip retrieving users for a group based on the required attributes query parameter in the SCIM GET groups API

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java

Resolves https://github.com/wso2/product-is/issues/10631

Introduce primary login identifier for scim user operations

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves https://github.com/wso2/product-is/issues/9800

Fix the issue with group patch operation when using email as username

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java

$subject.
Fixes https://github.com/wso2/product-is/issues/10897.
Fixes https://github.com/wso2/product-is/issues/10898.

Fix SCIM sorting issue while listing users.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves: https://github.com/wso2/product-is/issues/10723 and https://github.com/wso2/product-is/issues/10846

Add changes to Group endpoint to support primary login identifier.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Issue: https://github.com/wso2/product-is/issues/11022
Front porting https://github.com/wso2-support/identity-inbound-provisioning-scim2/pull/147

Remove user's group retrieval if groups are excluded.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

When the Login identifiers are defined, the SCIM filtering is not working for conditions that have more than one attribute. This PR fixes that issue.
Partially resolves, https://github.com/wso2/product-is/issues/10631

Fix issues in scim filtering 

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fixes https://github.com/wso2-enterprise/asgardeo-product/issues/1799.
Omit wso2.roles and wso2.groups claims when building SCIM user object because both roles and groups attributes are separately handled after SCIM user object is built

Fix user GET response

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

> Fixing https://github.com/wso2/product-is/issues/11249

Fixing "SCIM2 group list response shows primary roles directly deleted from the LDAP"

---

components/org.wso2.carbon.identity.scim2.provider/src/main/webapp/META-INF/context.xml

Skip all jars in tld scan
Related to https://github.com/wso2/product-is/issues/11531

Skip all jars in tld scan

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fixes previous behaviour when isRoleAndGroupSeparationEnabled is set to true but  isGroupsVsRolesSeparationImprovementsEnabled is set to false.
This PR fixes the above said backward compatibility which was caused by https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/336.
Fixes https://github.com/wso2-enterprise/asgardeo-product/issues/3337.
Related issue: https://github.com/wso2/product-is/issues/11327

Fix backward compatibility when group role separation is enabled but it's improvements are disabled

---

pom.xml

change nexus http link to https

change nexus http link to https

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolverTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentityResourceURLBuilderTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/resources/testng.xml

Test cases for SCIMRoleManager, DefaultSCIMUserStoreErrorResolver, IdentityResourceURLBuilderTest

Test cases - SCIMRoleManager, DefaultSCIMUserStoreErrorResolver, IdentityResourceURLBuilderTest

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Test cases for getUser, getUserSchema and getGroupPermissions.

Unit tests for getUser, getUserSchema and getGroupPermission methods

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Unit tests for deleteUser, deleteMe and listUsersWithPost methods

Add unit tests for deleteUser, deleteMe and listUsersWithPost methods

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Add unit tests to test unhappy paths of createUser method

Add unit tests for createUser method

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Resolves: https://github.com/wso2-enterprise/asgardeo-product/issues/2726#issuecomment-845015970

Fix getting the address claim value 

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandler.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fixes https://github.com/wso2-enterprise/asgardeo-product/issues/3815

Add diagnostic logs

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolver.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolverTest.java

Resolves https://github.com/wso2/product-is/issues/11976
Throw 400 error code for UserStoreClientExceptions.

Fix handling client errors

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java

Resolves https://github.com/wso2/product-is/issues/12006
Related PR: https://github.com/wso2/carbon-identity-framework/pull/3587

Improve error handling in Role update operation

---

features/org.wso2.carbon.identity.scim2.common.feature/resources/charon-config.xml
features/org.wso2.carbon.identity.scim2.common.feature/resources/org.wso2.carbon.identity.scim2.common.feature.default.json
pom.xml

Change custom-user-schema-uri value from "urn:scim:custom:schema' to  "urn:scim:wso2:schema"

Change custom-user-schema-uri value to urn:scim:wso2:schema

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
pom.xml

Improve error handling

---

features/org.wso2.carbon.identity.scim2.common.feature/resources/charon-config.xml
features/org.wso2.carbon.identity.scim2.common.feature/resources/org.wso2.carbon.identity.scim2.common.feature.default.json
pom.xml

Revert this PR to remove the changes of moving "custom" to "wso2"

Revert the PR "Change custom-user-schema-uri value to urn:scim:wso2:schema"

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

$subject
Address https://github.com/wso2/product-is/issues/11889
Address https://github.com/wso2/product-is/issues/11857

Fix SCIM groups PATCH operation to support LoginIdentifier and issue with filtering

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
pom.xml

Define framework version range in import packages

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
pom.xml

Update isJITProvisionEnhancedFeatureEnabled method name

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java

This PR is to handle identity claim update for JIT provisioned users as all attribute update is blocked for JIT provisioned users.
Related issue:https://github.com/wso2-enterprise/asgardeo-product/issues/5315

Handler identity claim update for JIT provisioned users

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves https://github.com/wso2/product-is/issues/12188

Fix group meta attributes in the response

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

**Purpose**
> $subject
> Related Issue - [#10839](https://github.com/wso2/product-is/issues/10839)

Fix http response of SCIM create/update group when the roleName policy mismatch 

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMGroupResolver.java

Prepend domain to the name

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCustomSchemaProcessor.java
pom.xml

Note $Subject
These changes can be reverted after  fixinghttps://github.com/wso2/product-is/issues/12451
Will create and add a product-is issue  with possible erroneous flows

Consider all custom schema attributes as not mandatory

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Below improvements are included in this fix:
- Fix the issue on filtering users with hybrid roles when pagination params are present.
- Fix the case sensitivity issue when filtering with groups in the SCIM2 Users endpoint.

Fix case sensitivity issue and pagination params issue when filtering with groups in the SCIM2 Users endpoint

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolverTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentityResourceURLBuilderTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java

Address comments on https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/346

Address review comments in old PRs

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java

Break the user claim update flow if the updated groups do not exist in the system.

Validate the list of groups before updating the user claims

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
pom.xml

**Depends on https://github.com/wso2/charon/pull/359**

Add support for core schema in /schemas endpoint

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Resolves https://github.com/wso2/product-is/issues/12813

Get totalResults without depending on pagination params in filter query

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.provider/pom.xml
features/org.wso2.carbon.identity.scim2.common.feature/pom.xml
features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml
features/org.wso2.carbon.identity.scim2.server.feature/pom.xml
pom.xml

**Proposed changes in this pull request**
Change the version to 1.5.128-SNAPSHOT
Change the scm tag

Change the version to SNAPSHOT

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
pom.xml

Add Update commits to 1.5.x

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
pom.xml

**Purpose**
Related Issue-  https://github.com/wso2/product-is/issues/11766			
**Merge https://github.com/wso2/carbon-kernel/pull/3163, https://github.com/wso2/carbon-identity-framework/pull/3884 before merging current PR.**

Fix Identity claim filtering

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java

Reverts wso2-extensions/identity-inbound-provisioning-scim2#409

Revert "Adding default regex pattern to restrict special characters in user claim inputs"

---

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config

Remove backup code claim from scim

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

- Fix userstore domain inconsistency in Groups
- Resolves https://github.com/wso2/product-is/issues/13839

Fix userstore domain inconsistency in Groups

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java
pom.xml

* $subject
* Fix https://github.com/wso2/product-is/issues/13823
* https://github.com/wso2/carbon-identity-framework/pull/4060
Do not merge. Need to bump the identity.framework.version and carbon.kernel.version

Set the totalResults Value correctly in the Response for SCIM2 Paginated Get Roles Request

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMTenantMgtListener.java
pom.xml

$Subject
Part of fix https://github.com/wso2/product-is/issues/13959

Skip tenant admin's scim claim update in the tenant creation of organization creation flow

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/GroupDAO.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMGroupResolver.java

Depends on https://github.com/wso2/carbon-kernel/pull/3342
Resolves https://github.com/wso2/product-is/issues/14067

Fix group id resolver to include the group domain name

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
pom.xml

Issue: https://github.com/wso2/product-is/issues/14060
Please note that location header URIs will not be fixed with this change as we currently don't have a similar for tenant URLs as well.
Depends on: https://github.com/wso2/carbon-kernel/pull/3358

Modify API response URLs for organization specific routing scenarios

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.provider/pom.xml
features/org.wso2.carbon.identity.scim2.common.feature/pom.xml
features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml
features/org.wso2.carbon.identity.scim2.server.feature/pom.xml
pom.xml

Change development version to 3.0.0-SNAPSHOT

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.provider/pom.xml
features/org.wso2.carbon.identity.scim2.common.feature/pom.xml
features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml
features/org.wso2.carbon.identity.scim2.server.feature/pom.xml
pom.xml

Bump kernel version

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java

$subject
https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/29

Fix SCIM resource location paths for organization management

---

components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.provider/pom.xml
features/org.wso2.carbon.identity.scim2.common.feature/pom.xml
features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml
features/org.wso2.carbon.identity.scim2.server.feature/pom.xml
pom.xml

Bump version to 3.3.0-SNAPSHOT

Bump version to 3.3.0-SNAPSHOT

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

https://github.com/wso2/product-is/issues/14986
Frontport: https://github.com/wso2-support/identity-inbound-provisioning-scim2/pull/274
This "checkForSCIMDisabledHybridRoles"[1] method was introduced[2] earlier to generate SCIM metadata for hybrid roles when SCIM is disabled. This issue was reported for IS-5.11.0 and when the group role separation is enabled this will not be called due to the fix[3].
The "checkForSCIMDisabledHybridRoles"[7] method is only required when a customer migrates from SCIM-disabled products to generate SCIM metadata for hybrid roles when the group role separation is also disabled. By calling this method, metadata generation is done at the role retrieval level. This was done by checking for hybrid roles and generating the scim-related metadata for the affected …

Fix out of memory issue when SCIM user retrieval

---

.github/workflows/pr-builder.yml
README.md
components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandlerTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManagerTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java
components/org.wso2.carbon.identity.scim2.provider/pom.xml
features/org.wso2.carbon.identity.scim2.common.feature/pom.xml
features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml
features/org.wso2.carbon.identity.scim2.server.feature/pom.xml
pom.xml

Get latest changes from master and update pom to 4.0.0 major version for IPK.

Update pom to Major Development Version

---

components/org.wso2.carbon.identity.scim2.provider/src/main/resources/META-INF/spring.schemas
components/org.wso2.carbon.identity.scim2.provider/src/main/webapp/WEB-INF/cxf-servlet.xml

> Remove specific versions for spring-beans and spring-context to avoid searching online for schemas which causes failure to start up offline.

Resolve scim2 webapp not starting up when offline

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java
pom.xml

Resolves: https://github.com/wso2/product-is/issues/15154
Related PRs: https://github.com/wso2/carbon-identity-framework/pull/4342

Performance Improvement to SCIM Role PATCH operation

---

components/org.wso2.carbon.identity.scim2.provider/pom.xml
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/util/SupportUtils.java
pom.xml

- https://github.com/wso2/product-is/issues/14767
- https://github.com/wso2-extensions/identity-governance/pull/644

Add ask password confirmation code to header when notifications are managed by client

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java

Fixes: 
- https://github.com/wso2-enterprise/asgardeo-product/issues/14403
This PR changes the CharonException which is treated as a server exception. But in this case since the userId is provided by client, which we should consider as client exception (Bad Request with InvaliValue ScimType).

Fix Client error

---

components/org.wso2.carbon.identity.scim2.provider/src/main/webapp/WEB-INF/web.xml
pom.xml

- https://github.com/wso2/product-is/issues/15520

Move carbon.ui.filters.cache to carbon.tomcat.ext.filter

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
pom.xml

Add length validation for attributes

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

* Check if the users are already available in the groups before adding them to the group

Check users are already avaialble in the group before adding them

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
pom.xml

> Fixes https://github.com/wso2/product-is/issues/15986
> Depends on https://github.com/wso2/charon/pull/384
> Please refer https://github.com/wso2/product-is/issues/15986#issuecomment-1591804907

Performance Improvement to SCIM Group PATCH operation

---

.github/workflows/pr-builder.yml
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/GroupDAO.java

This PR will fix the issue related to the scim2 group and role endpoints. Refer the following issues for more details.
- https://github.com/wso2/product-is/issues/15749
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/459

fix scim2 groups issue

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/BulkResource.java
pom.xml

$subject
- https://github.com/wso2/charon/pull/394
- Merge charon [PR](https://github.com/wso2/charon/pull/394) before this PR.

Provide v2 role support in `scim2/Bulk` API.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java

Add complex filtering support for v2 role filtering

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java

**Related issue** 
- https://github.com/wso2/product-is/issues/17481
**Related PR**
- https://github.com/wso2/carbon-identity-framework/pull/5128

Fix invalid permission error handling issues

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java

$subject
- https://github.com/wso2/product-is/issues/17733

Fix role v2 associated groups update

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java

This PR fix issue with user can't be assigned to multiple roles with same name in different audiences
- https://github.com/wso2/product-is/issues/17651

Fix role v2 same role name user update

---

pom.xml

Related to: https://github.com/wso2/product-is/issues/17825

Update Charon version.

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

$subject
Replace "==" with equals() method to compare string values

Refine string value comparison logic to improve code quality

---

features/org.wso2.carbon.identity.scim2.common.feature/resources/charon-config.xml.j2
features/org.wso2.carbon.identity.scim2.common.feature/resources/p2.inf

**$subject**
Resolves https://github.com/wso2/product-is/issues/16916

Pack charon-config.xml.j2 to the product

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMGroupResolver.java

Fix braking backward compatibility when storing location attribute

Fix error when saving the location attribute

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java

$subject
- https://github.com/wso2/product-is/issues/19477

Not equal support for the filter options of roles listing

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Skip logging client errors while resetting password

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix for masking username

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Reverts wso2-extensions/identity-inbound-provisioning-scim2#555

Revert "Fix multi-attribute user filter with count provided."

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

$subject
- https://github.com/wso2/product-is/issues/20981

Fix group list with count issue

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

$subject
- https://github.com/wso2/product-is/issues/21257

Improve user filtering user search

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
pom.xml

- https://github.com/wso2/product-is/issues/20548
- https://github.com/wso2/product-is/issues/20496
- https://github.com/wso2/product-is/issues/21242
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/562
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/555

User filtering advance improvements

---

.github/workflows/pr-builder.yml
codecov.yml
components/org.wso2.carbon.identity.scim2.common/pom.xml
components/org.wso2.carbon.identity.scim2.provider/pom.xml
features/org.wso2.carbon.identity.scim2.common.feature/pom.xml
features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml
features/org.wso2.carbon.identity.scim2.server.feature/pom.xml
pom.xml

This PR adds Codecov and JaCoCo configurations to the repository.

[Automated PR]Add Codecov and JaCoCo configurations

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
pom.xml

$subject
Related issue:
- https://github.com/wso2/product-is/issues/21822
When this PR should be merged:
- After merging https://github.com/wso2/carbon-identity-framework/pull/6190

Get role count for a filter in a given tenant

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolver.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolverTest.java

Fix https://github.com/wso2/product-is/issues/22709
Now, the response looks like follows

Fix NPE occurred on unmodifiable claim update in shared profile

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
pom.xml

Part of https://github.com/wso2/product-is/issues/22610

Add getSyncedUserAttributes method

---

components/org.wso2.carbon.identity.scim2.provider/src/main/webapp/WEB-INF/web.xml

Fix https://github.com/wso2/product-is/issues/22914

Support scim2/Me in with /o/ path

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
pom.xml

- https://github.com/wso2/product-is/issues/23042

Fix custom attributes in system schema

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/MeResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
pom.xml

> $subject
Depends on: https://github.com/wso2/carbon-identity-framework/pull/6503
-

Update flow name in scim2/user and scim2/me update

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Fix the issue of not honoring the config 'consider_total_records_for_total_results_of_ldap' when request doesn't contains filter parameters.
- https://github.com/wso2/product-is/issues/23484
- The `consider_total_records_for_total_results_of_ldap` config is only considered when the request contains the filter parameter [1]. However, when listing users without a filter, the total count will contain the number of items per page if the userstore is LDAP[2]. 
- With this fix we have improved the the litsUser method as well to honour the config`consider_total_records_for_total_results_of_ldap` for requests without a filter as well. 
- If `consider_total_records_for_total_results_ldap` is enabled, 'totalRecords' will be the total number of records matching the client query. Otherwise (default), …

Fix the issue of not honoring the config  'consider_total_records_for_total_results_of_ldap'

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

This PR removes immutable claims from the old claim list and remove the claim difference between old claim list of the user and new claim list of the user
- https://github.com/wso2/product-is/issues/23644

Remove immutable claims from claims lists for update user in UserManager

---

components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/internal/action/PreUpdateProfileActionExecutorTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/test/constants/TestConstants.java

Fix check style

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMGroupResolver.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtil.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListenerTest.java
pom.xml

Resolves https://github.com/wso2/product-is/issues/23856
Depends on https://github.com/wso2/carbon-kernel/pull/4287

Support dual write option for groups

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/GroupDAO.java

Add review suggestions

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

$subject
- https://github.com/wso2/product-is/issues/23946

Fix incorrect handling of trailing whitespaces in user patch endpoint

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapperTest.java

The primitive data types like strings, integers and decimals can have multiple values. But we have only considered strings  up to now. This PR is initiated to handle for integers and decimals also.
- https://github.com/wso2/product-is/issues/24253

Fix Integer multi valued issues

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

Parent issue
- https://github.com/wso2/product-is/issues/24259

Publishing user registration failure event

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/MeResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
pom.xml

Improving the flow context of registration.
This PR should be merged after following PR and the version bump.
- https://github.com/wso2/carbon-identity-framework/pull/6875
Parent issue
- https://github.com/wso2/product-is/issues/24259

Improving the flow context of registration

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/util/SupportUtils.java

Parent issue
- https://github.com/wso2/product-is/issues/24496

Refactoring the ask password check

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java

Modifying the SCIM schema for ask password flow.
Parent issue
- https://github.com/wso2/product-is/issues/24496

Modifying the SCIM shema for ask password flow

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/cache/SCIMAgentAttributeSchemaCache.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/cache/SCIMAgentAttributeSchemaCacheEntry.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/cache/SCIMAgentAttributeSchemaCacheKey.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/handlers/SCIMClaimOperationEventHandler.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/component/SCIMCommonComponent.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/cache/SCIMAgentAttributeSchemaCacheTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java
components/org.wso2.carbon.identity.scim2.common/src/test/resources/testng.xml
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/extensions/AgentResourceManager.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/AgentResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/webapp/WEB-INF/web.xml
pom.xml

Fix for : https://github.com/wso2/product-is/issues/24535
Core Components:
1. **Agent Resource Manager**: A new `AgentResourceManager` class extending `UserResourceManager` with agent-specific creation logic and validation
2. **SCIM2 Endpoint Registration**: Register `/Agents/*` endpoint mapping in the CXF servlet configuration
3. **Agent Schema Support**: 
- Agent-specific attribute schema handling and caching
- Custom schema utilities for agent flows
- Integration with existing SCIM2 schema framework
4. **Agent Context Management**: Thread-local context management to differentiate agent flows from standard user flows
5. **Caching Infrastructure**: Dedicated caching for agent attribute schemas (`SCIMAgentAttributeSchemaCache`)

Add /Agent CRUD endpoints

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Preventing user profile event at account lock and unlock
Parent issue
- https://github.com/wso2/product-is/issues/24581

Preventing user profile event at account lock and unlock

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java

Align registration success event flow with SCIM account status attributes
Parent issue
- https://github.com/wso2/product-is/issues/24598

Align registration success event flow with SCIM account status attributes

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Prevent mobile and email verification
Parent issue
- https://github.com/wso2/product-is/issues/24668

Prevent mobile and email verification

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/AgentResource.java

Skip password pattern validation at the agent flows

Skip password pattern validation at the agent flows

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

$subject
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Add agent attributes at filtering

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

> $subject
- https://github.com/wso2/product-is/issues/24784

Fix the system schema claims incorrectly identified as complex and multi valued if the SCIM claim is a registered name

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/BulkResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/GroupResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/MeResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/util/SupportUtils.java
pom.xml

Refactoring the flow sequence
This has breaking changes with following repos
1. Framework https://github.com/wso2/carbon-identity-framework/pull/7065
2. Governance https://github.com/wso2-extensions/identity-governance/pull/1003
Parent issue
- https://github.com/wso2/product-is/issues/24939

Refactor to flow sequence

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java

> Previously boolean type values are not correctly resolved from isAskPassword(). This PR fixes that issue
- https://github.com/wso2/product-is/issues/24983

Resolve askPassword attribute value resolving issue

---

pom.xml

Bump framework 396

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/util/FlowUtil.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/MeResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/util/SupportUtils.java

Continuing the initiating persona
Parent issue
- https://github.com/wso2/product-is/issues/24869

Continuing the initiating persona

---

pom.xml

- Resolves https://github.com/wso2/product-is/issues/25029
- Related PR : https://github.com/wso2/charon/pull/443

Charon version bump

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java

Enabling flows for the account lock and disable
Parent issue
- https://github.com/wso2/product-is/issues/25272

Enabling flows for the account lock and disable

---

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/MeResource.java
components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java

Refactoring the user delete flow
- https://github.com/wso2/product-is/issues/25272

Refactoring the user delete flow

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/action/PreUpdateProfileActionExecutor.java

> $subject
- https://github.com/wso2/product-is/issues/25543

Change an exception to a warn log when accessing org is not present in the identity context in scim2 PATCH flows

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java

> $subject
- https://github.com/wso2/product-is/issues/25560

Provide the date and epoch data type support

---

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListenerTest.java
pom.xml

> When a regular expression is defined for a multi-value attribute, it does not validate each value; rather, it validates the attribute value as an array.
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/722
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that …

[Next] Confusion in defining a regex for multi-value attributes
