wso2-extensions/identity-inbound-provisioning-scim2

.travis.yml
As per https://github.com/travis-ci/travis-ci/issues/7884 oraclejdk7 is no longer supported.
=> Updating travis build JDK to fix build failure

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/GroupResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/util/SCIMProviderConstants.java, pom.xml
Introducing logical operators for SCIM2 filters with pagination. Here we going to support 'AND' logical operator for following SCIM2 filters such as eq, sw, ew, co. The user can query user details using multi-attribute search filters.
Also, support pagination within a particular user store, where the end user can specify which user store he/she wants to perform the paginated search. Otherwise, perform the paginated search on PRIMARY user store.
If the end user didn't specify pagination, then perform filtering on all available user stores and retrieve.
For further details,
[https://docs.google.com/document/d/1rsJgQ7g8dAJL0pW1biLe6iRXHbZKmJsTCEJncVHJ5hQ/edit?usp=sharing](url)
=> Introducing 'AND' logical operators for multi attribute user filtering with pagination

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
This PR addresses the following issues.
* https://github.com/wso2/product-is/issues/4175: Inconsistency in SCIM2 group's displayName attribute format when filtering via different endpoints
* https://github.com/wso2/product-is/issues/3973: Eq should strictly check for the String match (in this case cross user store search should not be performed)
In order to maintain the backward compatibility, this functionality is enabled with following configuration.
`	<EnableFilteringEnhancements>true</EnableFilteringEnhancements> `
=> Fix inconsistency in SCIM2 group's displayName attribute format when filtering via different endpoints

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
**Description**
SCIMUserManager has the userNames array. Removed the duplicated username in the method filterUsers using a if condition
Product IS uses the identity-inbound-provisioning-scim2 v1.2.12
Resolved the issue [4181](https://github.com/wso2/product-is/issues/4181)
=> Fixed the issue Filter user by email address returns duplicate results 4181

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
Fix wso2/product-is#3847
This problem was caused by 2 issues in the implementation
1. When contains operator is used it creates a modified value by closing the value with wild card characters. As an example, SECONDARY/username will be transformed to *SECONDARY/username*. PR solves this issue by correcting it as SECONDARY/*username*. 
2. When using JDBC user stores along with SCIM implementation will skip username checks. This issue has been addressed by https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/132
=> Fix  wso2/product-is#3847

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
from [product-is 3487](https://github.com/wso2/product-is/issues/3487):
Currently, the `EnterpriseUser` key is used in SCIM user creation to specify the properties of a user specified in `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User`.
Per [RFC 7643 section 3.3](https://tools.ietf.org/html/rfc7643#section-3.3), "Except for the base object schema, the schema extension URI SHALL be used as a JSON container to distinguish attributes belonging to the extension namespace from base schema attributes.".  See also the example User JSON in [section 8.3](https://tools.ietf.org/html/rfc7643#section-8.3).
I've set this pull request against master (2.x) because it is a breaking change from the current implementation
=> change EnterpriseUser scim property to match its schema URN.  resolves product-is 3487

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
- Fix wso2/product-is#5088
The issue was caused by non-scim users user being added to the result set. Since they don't have a scim id it returns "invalidValue","detail":"Required attribute id is missing in the SCIM Object." response.
=> Fix #5088:SCIM2 user listing with an offset for a secondary user store is not working properly

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/GroupResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java, pom.xml
- FIX [wso2_product_is#5106](https://github.com/wso2/product-is/issues/5106)
- Previously int variables were used to hold values for count and startIndex. Therefore, variables could not hold Null state values.
- In the fix Count and startIndex variables were set as Integer objects so that they can hold Null state values.
- A new method was declared to process the count and startIndex params in the groups endpoint.
=> FIX user specifying count zero

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
Fix: wso2/product-is#5333
Approach
- The UpdateGroup method, validates whether there has been an update or not and populate variable `updated`.
- When we try to add duplicate member to an existing group, in the previous case `newGroup` was returned. The issue is, in newGroup there can be duplicate entries even though `updated` param is set to `false`.
- This `update` var will be `True` only if there is a change. Therefore the value will be `false` for duplicate entries.
- In this approach, if the updated param is `false`, `oldGroup` is returned because there are no duplicate entries and vise versa.
- In this approach, if the updated param is `true`, we'll query again and return the updated group.
=> Fix for Remove Duplicate Members From the Patched Group

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java
A change has been done in WSO2 IS 5.8.0 to be compliant with SCIM 2 specification regarding urn:ietf:params:scim:schemas:extension:enterprise:2.0:User. 
attributeName "EnterpriseUser" has been renamed to "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
But the underlying code is not compatible with this change. AttributeName is not split well. A regression has been introduced in commit b29a2b8e5b2f98aa7d03396c4ab519123d9c7e32 for GET operations.
This fix change the parsing code of AttributeName to manage this use case.
Revert the change
N/A
Fix AttributeName splitting when performing GET on a user with  urn:ietf:params:scim:schemas:extension:enterprise:2.0:User attributes.
N/A
N/A
N/A
N/A
N/A
- Followed secure coding standards in …
=> fix regression to manage schema extensions

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
Resolves wso2/product-is#5954
In this PR it supports hybrid roles (Application &Internal) listing and filtering.
Listing can be done using a new 'domain' query param.
Filtering can be done in 2 ways.
1.using 'domain' query param
2.using '{domain}/' prefix
Example listing request:
curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?domain=Application'
Example filtering request with domain parameter:
curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?filter=displayName+eq+Apple&domain=Internal'
Example filtering request with domain prefix:
curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?filter=displayName+sw+Application/App'
=> Support hybrid role listing & filtering with domain parameter for SCIM

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
During the add user event, we add the mapped local claim in the listener
https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/c695cb6ac05376678f10367d36faa5bf5c866227/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java#L410
But in the doPreSetUserClaimValues, we have added the 'lastModified' SCIM claim, which causes the https://github.com/wso2/product-is/issues/6003 during updating the user profile when the 'lastModified' is mapped to an identity claim
(fix https://github.com/wso2/product-is/issues/6003)
=> Use the local mapped claim of the lastModified

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponent.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponentHolder.java, components/org.wso2.carbon.identity.scim2.provider/pom.xml, features/org.wso2.carbon.identity.scim2.common.feature/pom.xml, features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml, pom.xml
Refer: wso2/product-is#5284 for the context.
This PR implement necessary new methods introduced in SCIM User Manager (introduced with https://github.com/wso2/charon/pull/260) to populate user schema details dynamically to match with claim metadata.
=> Add scim user schema endpoint impl

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/GroupResource.java
With changes done for https://github.com/wso2/product-is/issues/6918 we can enable a config that would return a 204 response for Group PATCH requests.
However, if attributes are requested then we need to always send a 200 OK response
=> Improve group patch to return 200 OK always if attributes are requested

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java, features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
- Introduces new attribute to Enterprise User Extension to represent verification pending emails.
- Fixes NPE in constructSCIMObjectFromAttributesOfLevelThree method when there is no type property in the attribute. (https://github.com/wso2/product-is/issues/7512)
This PR is related to feature: https://github.com/wso2/product-is/issues/7183
This PR should be merged after https://github.com/wso2-extensions/identity-userstore-ldap/pull/34
=> Add verificationPendingEmail attribute to scim2 schema extension.

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
**Description**
https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/243/ resolves https://github.com/wso2/product-is/issues/7320 partially. 
Eventhough the secondary userstorre is a JDBC one, the fix https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/243/  provides the correct totalResult for the following CURL command:
`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?startIndex=1&count=2&domain=<secondary user store domain>'`
only if the primary userstore is a JDBC. 
The fix in this PR is able to provide the correct totalResult in pagination if the specified domain is a JDBC userstore domain.
=> Correct totalResult in pagination when secondary userstore is JDBC and primary userstore is LDAP

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, pom.xml
Implement enterprise user schema retrieval for SCIMUserManager for new method definition in UserManager interface(https://github.com/wso2/charon/pull/279).
Related to issue: https://github.com/wso2/product-is/issues/5284
https://github.com/wso2/charon/pull/279
=> Add enterprise user schema impl to SCIMUserManager

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
https://github.com/wso2/product-is/issues/8309
https://github.com/wso2/product-is/issues/8294
If  Exception occurred in the try method catch throw Charon Exception with scimUser.getUserName() in the message body. This may cause null point exception because scimUser defined as null before try method.
Instead of scimUser, we can use core user to get UserName
=> Refactor Exception Message

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
Fixes https://github.com/wso2/product-is/issues/6101
**Requirement**
The user portal should be able to disable updating the user claims if the user is in a read-only user store. Therefore there should be a way to get the detail of whether the user-store is read-only or not when retrieving the user details by calling the SCIM GET API.
**Approach**
1. We have introduced a new claim as `http://wso2.org/claims/identity/isReadOnlyUser` to the WSO2 claim dialect and it is mapped with the `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:isReadOnlyUser` of the WSO2 enterprise user dialect. ( https://github.com/wso2/carbon-identity-framework/pull/3033)
2. The SCIM attribute is defined such that it will be returned only when it is requested.
3. Therefore when calling the SCIM endpoint …
=> Introduce a new claim to check user's mutability

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
Resolves https://github.com/wso2/product-is/issues/9124
With this improvement SCIM2 user endpoints return the user core errors in the SCIM2 response. To enable it we have to add below configuration in the deployment.toml file.
```
[scim2]
notify_userstore_status = true
```
=> Improve scim2 response messages

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
Adds a new attribute to the Enterprise User Extension to represent verification pending mobile number.
Related to issue - https://github.com/wso2/product-is/issues/9045
=> Add claim to store verification pending mobile number

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
Resolve https://github.com/wso2/product-is/issues/9907
Not throwing an error when iterating through the user stores. Therefore when an error occurred in one user store, the user search of other user stores will not get affected due to this.
=> Not throwing an error when iterating though the userstores

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
> Resolves https://github.com/wso2/product-is/issues/9859
> The SCIM2 `.search` request fails for all (Users, Groups, Roles) endpoints when no count attribute is declared in the request body. Ideally, when the count attribute is not specified, the default pagination value must be used when returning results. The `pagination-default-count` was not being read properly from the `charon-config.xml` file. This PR adds the relevant constants needed and adds the value to the config object.
> Merge with https://github.com/wso2/charon/pull/294
=> Pagination count config value read from charon-config.

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
> Handle the username validation by checking the userstore case sensitivity in SCIM user update.
> Fixed a test case.
> Fixes : wso2/product-is#9854
> Please merge this PR after https://github.com/wso2/carbon-kernel/pull/2829
=> [public]Handle username validation with case sensitivity of the userstores

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
This PR introduces a new claim 'verifyMobile' to the enterprise schema extension.
Part of the fix for : https://github.com/wso2/product-is/issues/10358
=> Add claim to store verifyMobile claim used to enable mobile verification

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
This PR fixes a null pointer exception that occurs while adding users when workflow engagements are involved.
Resolves : https://github.com/wso2/product-is/issues/10390
=> Fix NPE while adding users when workflow engagements are involved

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
> Resolves https://github.com/wso2/product-is/issues/9548
> The `attributeName` is used as the key when building the extension config map. This causes the configs having the same `attributeName` to get overwritten by the last config being read. Making the attribute names unique resolves this issue. This would not cause an issue when the schema is being read as the `attributeURI` is used to pull configs from the schema.
=> Sub attribute names made unique in the scim2-schema-extension.config

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
Reverting this as this would change the format of the request payloads.
=> Revert "Sub attribute names made unique in the scim2-schema-extension.config"

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/extenstion/SCIMUserStoreErrorResolver.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/extenstion/SCIMUserStoreException.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolver.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponent.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponentHolder.java
Resolve wso2/product-is#10468
- A new extension point has been introduced in the SCIM component to provide proper HTTP error code mapping. Developers can use this extension point to define specific errors and matching error codes to be sent in the API response when they develop their own custom user store managers.
- We register a default implementation that can be used to resolve errors of the default user store managers of the product.
- The extension point requires to define an order for each implementation, which will be used to loop if more than one registered implementations are found. The impl with the highest order value will be executed first. The default implementation has the order value 0.
Note: This change will not change any error messages or exceptions of the current SCIM …
=> Propagate User Store Errors Through SCIM API

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMTenantMgtListener.java
In the current implementation of the SCIMTenantMgtListener, we cannot disable the handler using configurations. With the improvement in this PR, the product admins can disable the lister if needed.
=> Improve SCIMTenantMgtListener with disable capability

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolver.java, pom.xml
:heart_eyes: Fixes https://github.com/wso2/product-is/issues/10611.
:grimacing: Depends on https://github.com/wso2/carbon-kernel/pull/2859.
:speech_balloon: While SCIM user filtering, the underneath user store manager throws a client exception with a specific error code. This PR modifies the code to read that error code and gracefully handle the error.
:raising_hand: Do not merge until,
=> Gracefully handle invalid domain name while user filtering

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, pom.xml
:heart_eyes: Fixes https://github.com/wso2/product-is/issues/10509.
:speech_balloon: While Iterating user stores to list users, the `carbonUM` variable value gets reassigned with the next user store manager. However, this is a class-level variable that should not be modified because if this object instance is reused, that can cause unexpected behavioral changes. This PR instruct the code to use a method-level variable.
🙋 Do not merge until,
=> Use method level variable to iterate through userstores

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
Fix: https://github.com/wso2/product-is/issues/10878 and do some code formatting.
- At the moment only the "COMPLEX" and "STRING" type is returned as the attribute type for all the SCIM attributes in the `/scim2/Schema` API response.
- But, in the urn:ietf:params:scim:schemas:extension:enterprise:2.0:User schema extension, we can define attribute type to be boolean.
- REST API should send the correct type for these extension attributes
- Format the code in the respective class
=> Set attribute type of scim2 extended attribute schema response based on configuration

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java
When converting the User core object to SCIMObject, skip the invalid attributes.
Resolves: https://github.com/wso2-enterprise/asgardeo-product/issues/1679
=> Construct SCIMObject skipping the invalid attributes

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
Since dateOfBirth is an attribute that takes user input, having datatype as `datetime` affects the UX negatively.
Further SCIM spec doesn't have a data type as `date` only to save dates.
Hence change the data type to `string`. Refer: https://mailarchive.ietf.org/arch/msg/scim/-dh881kMaDBryhDbjAZKknvMy2o/
Resolves part of:https://github.com/wso2-enterprise/asgardeo-product/issues/1679
=> Change datatype of dateofBirth scim claim

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
When the local claim of dob ("http://wso2.org/claims/dob") is considered as a string in the SCIM schema after https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/330 is merged. 
and currently, there is no regex configured for local dob claim.
Here we validate the dob against the configured regex or the default regex : `^\d{4}-\d{2}-\d{2}$`, in SCIMUserOperationListener 
when adding a user and updating a user
Resolves part of https://github.com/wso2/product-is/issues/11226
=> Regex validation for date of birth claim value

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
Resolves https://github.com/wso2/product-is/issues/8466
To support this, we need to modify the permission for delete operation. Currently the permission is 
```
<Permissions>/permission/admin/manage/identity/usermgt/delete</Permissions>
<Scopes>internal_user_mgt_delete</Scopes>
```
The user need to have these permission and scope. Else we can modify it via the config
=> Add delete operation support for scimMe

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java
Fixes part of wso2/product-is#11226
If the user added dob is not matching with the configured regex, returns a userStoreClientException.
The admin can configure the regex validation error message under the local claim properties with key = `RegExValidationError` as follows.
If this error is configured, the user will be prompted that configured error.
Otherwise, the default regex validation error will be shown.
=> Return userStoreClientException on dob regex validation failure

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/AbstractResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/BulkResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/GroupResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/MeResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/ResourceTypesResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/RoleResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/SchemaResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/ServiceProviderConfigResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
In the AbstractResource.handleCharonException method, decoder is a parameter that is never used. It is overwrite by a default value but not use nonetheless. It seems to be dead code.
If you remove this parameter and update all child resources, this makes some other variables unused in cascade (usually JSONEncoder and IdentitySCIMManager) and make some catch block unreachable (due to IdentitySCIMManager.getInstance removal).
=> remove unused encoder from AbstractResource.handleCharonException

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
Fixes https://github.com/wso2/product-is/issues/11328.
Groups is a read only attribute. Reference: https://tools.ietf.org/html/rfc7643#section-4.1.2
=> Fix immutable status of groups claim

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, pom.xml
Related to https://github.com/wso2/product-is/issues/11214
This PR has to be merged only after merging https://github.com/wso2/carbon-kernel/pull/2922
This PR is to add the following operations for SCIM user filtering with LDAP user stores. 
- ge (greater than or equal)
- le (less than or equal)
=> Add ge and le operations for SCIM user filtering

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
When executing a SCIM group update request to update the same group name with case sensitivity(Ex:- update mygroup to MyGroup), it will give a log warn saying "There is no updated field in the group:... " and will not update the group name. That issue will be fixed with this PR. 
Resolves: https://github.com/wso2-enterprise/asgardeo-product/issues/1655
=> Fix the case insensitivity issue when updating the group name

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, pom.xml
Fixes https://github.com/wso2/product-is/issues/11347.
Depends on https://github.com/wso2/carbon-kernel/pull/2936 and https://github.com/wso2/product-is/issues/11328. 
Optimize for SCIM2 user get requests to make use of the group vs role separation logic in the kernel.
Checklist
=> Utilize user.core logic in SCIM2 get user API

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java, pom.xml
- Resolves https://github.com/wso2/product-is/issues/11645
- Following configuration can be added to `deployment.toml` in order to enable read-only roles.
```
[system_roles]
read_only_roles = ["role1", "role2", "Administrator"]
```
- If it's defined those roles cannot be deleted, rename or update permissions via role API. Those roles can be identified with the `systemRole` meta attribute in the `GET /Roles` and `GET /Roles/{id}` response as below,
```
{
"displayName": "Administrator",
"meta": {
"systemRole": true,
"location": "https://localhost:9443/scim2/Roles/04ce8252-5b8a-4f1f-b00c-f889da4d0211"
},
"permissions": [
"/permission/"
],
"schemas": [
"urn:ietf:params:scim:schemas:extension:2.0:Role"
],
"groups": [
{
"display": "PRIMARY/Administrator",
"value": …
```
=> Add systemRoles configuration to identify read only roles

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
Earlier, tenant was picked based on SP. So it failed for saas apps (console). This PR will build custom schema claims from user's tenant
Fix issues in https://github.com/wso2/product-is/issues/11705
=> Build custom schema claims using user's tenant instead of sp's tenant

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapperTest.java
Address attributes were received incorrectly as below in the getUser response,
```
"addresses": [
{
"value": "100 Universal City Plaza Hollywood, CA 91608 USA",
"type": "work"
},
{
"value": "456 Hollywood BlvdnHollywood, CA 91608 USA",
"type": "home"
}
]
```
With this fix, it's corrected as for the specification [1] as below,
```
"addresses": [
{
"formatted": "100 Universal City Plaza Hollywood, CA 91608 USA",
"type": "work"
},
{
"formatted": "456 Hollywood BlvdnHollywood, CA 91608 USA",
"type": "home"
}
],
```
[1] https://datatracker.ietf.org/doc/html/rfc7643#section-4.1.2
Resolves https://github.com/wso2/product-is/issues/11801
=> Fix incorrect format of the addresses attribute

features/org.wso2.carbon.identity.scim2.common.feature/resources/charon-config.xml, features/org.wso2.carbon.identity.scim2.common.feature/resources/org.wso2.carbon.identity.scim2.common.feature.default.json
This PR contains the change of custom-user-schema-uri value from "urn:scim:custom:schema" to "urn:scim:wso2:schema". After fixing the integration tests in product-is .
* * *
1. Merge this PR
2. Bump the scim2 version in product-is
3. Merge the this PR in product-is ([product-is/pull/12042](https://github.com/wso2/product-is/pull/12042))
=> Change custom-user-schema-uri value from "urn:scim:custom:schema" to "urn:scim:wso2:schema"

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListenerTest.java, pom.xml
With the PR changes, editing the provisioned users synced attribute will be disabled based on the config introduced at [1]
Related issue: https://github.com/wso2/product-is/issues/12010
This PR should be merged after merging [1] and upgrading the framework version.
[1] https://github.com/wso2/carbon-identity-framework/pull/3589
=> Disable editing the provisioned user's attribute values

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
With the changes introduced by [1], it is required to add the userSourceId to scim2-schema-extension.config.
Resolves: https://github.com/wso2/product-is/issues/12185
[1] https://github.com/wso2/product-is/issues/12017
=> Add userSourceId to scim2-schema-extension.config

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
With the changes introduced `totpEnabled`, it is required to add the userSourceId to scim2-schema-extension.config.
https://github.com/wso2/product-is/issues/12530
=> Add TOTP Enabled claim

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
When retrieving the SCIM to local claim mapping, the current implementation provide tenant domain of thread local service provider. The expected tenant domain is the user's tenant domain.
=> Resolve tenant domain at retrieving SCIM to local claim mapping.

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolver.java
Fixes https://github.com/wso2/product-is/issues/12757
After the change:
response is: 400 Bad Request 
The response body is:
```
{
"schemas": [
],
"detail": "Invalid operation. User store is read only",
"status": "400"
}
```
=> Return 400 bad request for readonly userstore's user update

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
Internal Server error while updating a group with a non-existing user using PUT or PATCH requests.
=>  Fix Internal Server error while updating a group with non-existing user 

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
Resolves https://github.com/wso2/product-is/issues/12813#issuecomment-1004543880
Before the fix we have consider max user list value while calculating total results, hence if number of users is higher than max user list then total result shows the max user list value instead of actual number of users. 
With this fix we have introduced a config "ConsiderMaxLimitForTotalResult" to decide whether to consider the max user limit value during the total result. If the property disabled then total result will shows the actual number of users. Default value of this proerty is false. This fix has been added to scim endpoints /scim2/Users, scim2/Users?startindex=1&count=2(pagination),scim2/Users?filter=username+sw+ni(filtering)
=> Fix the issue in scim total results calculation

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
Purpose
Providing a backend validation to restrict special characters such as <>``"/ from user claim input values when the `enable_user_claim_input_regex_validation` configuration is enabled.
Resolves : [/product-is#13174](https://github.com/wso2/product-is/issues/13174)
Related configuration PR : [wso2/carbon-identity-framework#3940](https://github.com/wso2/carbon-identity-framework/pull/3940)
=> Adding default regex pattern to restrict special characters in user claim inputs

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
Could see below error logs when we:
1.  plug a secondary userstore which does not support uniqueID for groups feature
2. Call /groups or /scim2/me apis
```
TID: [-1234] [scim2] [2022-04-05 11:05:16,877] [7763389c-6c1a-4cae-8c36-ea4287d11062] ERROR {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - Group created date is not specified for group: admin
TID: [-1234] [scim2] [2022-04-05 11:05:16,878] [7763389c-6c1a-4cae-8c36-ea4287d11062] ERROR {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - Group last modified date is not specified for group: admin
```
This PR modifies those error logs into debug logs.
Related PRs:
https://github.com/wso2/carbon-kernel/pull/3251
=> Remove unnecessary error logs and add them as debug logs

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
* https://github.com/wso2/product-is/issues/13325
* Read the domain name from the userstore configurations and return it based on the `enable_filtering_enhancements` and `filter_users_and_groups_from_primary_domain` values.
=> Fix SCIM2 user filtering when primary userstore domain is changed

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java
* Remove getting the total count from DB for filterUsers. Filter user should show the number of results for the query in the `totalResults` attribute
* Fix https://github.com/wso2/product-is/issues/13823
=> Remove getting the total role count from DB for filterUsers

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
**Brief Description**
The Attribute type of boolean attributes such as `Active` are not correctly set in the scim2/Schemas API request. 
This PR fixes this issue (https://github.com/wso2/product-is/issues/13978)
**Related issues**
https://github.com/wso2/product-is/issues/13978
=> Set Correct Type for Boolean Attributes

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
**Purpose**
Resolve the issue https://github.com/wso2/product-is/issues/12813#issuecomment-1143122185
The issue is resolve by introducing a new configuration consider_total_records_for_total_results_ldap.
if consider_total_records_for_total_results_ldap is enabled;
'totalRecords' will be the total number of records matching the client query.
otherwise (default),
'totalRecords' will be the number of records per page.
Configuration related PR:
https://github.com/wso2/carbon-identity-framework/pull/4072
=> Fix the issue of totalResult parameter in SCIM user end point.

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, pom.xml
##Purpose
Resolves https://github.com/wso2/product-is/issues/13534 , https://github.com/wso2/product-is/issues/14122
ATM, renaming a group will remove the assigned roles of the group. This is due to not updating the UM_HYBRID_GROUP_ROLE table when renaming the group name. And also delete group won't remove the group from this table, due to this issue, if the new group name has old group name which has some assigned roles, those roles will be added to the currrent goup. Fixed both issues.
Dependent PR: https://github.com/wso2/carbon-kernel/pull/3355
=> Fix group rename and group delete issues

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.provider/pom.xml, features/org.wso2.carbon.identity.scim2.common.feature/pom.xml, features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml, features/org.wso2.carbon.identity.scim2.server.feature/pom.xml, pom.xml
In my attempts to implement cursor based pagination, it was noticed that the current method of returning the total number of results along with the list of users/roles/groups for GET requests and POST/.Search requests was to allocate the 1st position of a _List_ to carry the total results and the remainder to carry the users. 
It is not appropriate to store different data types in a _List_ therefore it was decided to refactor the code to change the return type to a custom java object which comprises of the users and total results. With the intention of supporting forwards cursor and backwards cursor for cursor pagination (Implemented [here](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/417/commits/59a04cbd536928b7d620134ba12322d0f62d40ad) and …
=> Changing the response type of GET and POST/.Search

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandler.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandlerTest.java
Public fix for [wso2-iam-internal #22](https://github.com/wso2-enterprise/wso2-iam-internal/issues/22)
When a name of a role is updated, in the [doPostUpdateRoleName](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/ba564119927f4649f1cdee724c0bea71d17f958c/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java#L623) method it tries to update the relevant entries in the IDN_SCIM_GROUP table. If IDN_SCIM_GROUP table does not contain information about that role, it throws an exception.
With the current behaviour, when trying to update the name of a SP, name of the application role related to the SP is updated with the new name. But, due to the exception thrown in the middle, SP’s …
=> Silently handle not having the group information in the SCIM tables

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
Resolves https://github.com/wso2/product-is/issues/12758
**Sample request:**
```
{
"Operations": [
{
"op": "replace",
"value": {
"members": [
{
"value": "bb69b872-217e-41ae-ac1f-3bc44a588434"
}
]
}
}
],
"schemas": [
"urn:ietf:params:scim:api:messages:2.0:PatchOp"
]
}
```
**Before the fix:**
NPE was logged and server return 500 error response
```
{
"schemas": [
],
"detail": "Error in performing the patch operation on group resource.",
"status": "500"
}
```
```
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.appendDomainToMembers(SCIMUserManager.java:4245)
at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.doUpdateGroup(SCIMUserMa …
```
=> Fix NPE when display name of a member is empty while updating a group

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
When a POST request (create user) is sent to the scim2/Users endpoint with an invalid user store name, the error response is misleading. (https://github.com/wso2/product-is/issues/14412)
```{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Cannot add user through scim to user store . SCIM is not enabled for user store <domain name>","status":"500"}```
This issue is fixed in this PR.
New response:
```{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"Invalid user store name.","detail":"Request is unparsable, syntactically incorrect, or violates schema.","status":"400"}```
=> Fix user store name incorrect response issue

.github/workflows/pr-builder.yml, README.md, components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandlerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/resources/testng.xml, components/org.wso2.carbon.identity.scim2.provider/pom.xml, features/org.wso2.carbon.identity.scim2.common.feature/pom.xml, features/org.wso2.carbon.identity.scim2.provider.feature/pom.xml, features/org.wso2.carbon.identity.scim2.server.feature/pom.xml, pom.xml
Update the repository from mockito 1 to mockito 2 to support JDK 11 and JDK 17 compilation.
After this PR is merged to the main branch, we can't build the branch on JDK 8
- openjdk "11.0.16.1"
- openjdk "17.0.4.1"
https://github.com/wso2/product-is/issues/14224
=> Support JDK 11 and JDK 17 Compilation

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
resolves - https://github.com/wso2/product-is/issues/15286
- According to the current implementations, if the user is in the primary user store, it is taking the domain name as PRIMARY from a hard-coded constant variable from the source code itself.
- This is resolved by reading the domain name from the realm configurations.
=> Fix SCIM2 multi attribute filtering when primary userstore domain name is changed

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
Check whether the attribute is custom schema attribute before assigning properties by considering the attribute name. If it's a custom schema attribute, it will be a simple, single valued attribute now on although it's name is hardcoded to consider it as a complex, multivalued attribute.
- https://github.com/wso2-enterprise/asgardeo-product/issues/14422
- https://github.com/wso2-enterprise/asgardeo-product/issues/11072
=> Fix considering custom schema attribute: entitlements as a multivalued attribute.

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
When building the resource URL of sub-organization users & groups , `o/<org-id>` is manually appended to make the resource path organization qualified. But when custom host configurations are added for the parent organization, asgardeo service url builder builds the public url of the sub-organization with `o/<org-id>` which results in having `o/<org-id>` twice in the resource URL.
With https://github.com/wso2/carbon-identity-framework/pull/4372 service URL builder is capable of appending the `o/<org-id>` part if the organization id is set in the context.
=> Fix sub organization user & group resource path with custom domains

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMGroupResolver.java
* Converting error logs of group endpoint into debug logs because we should not log any errors in the server if the group id does not exist (It's a client-side error, so throwing 404 would be enough).
* https://github.com/wso2/charon/pull/383
=> Convert the error logs into debug logs

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/util/SupportUtils.java
Fix SCIM bulk import with the ask password option fails where custom schema is set to null in the bulk user addition flow.
=> Fix SCIM bulk import with the ask password option failure

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, pom.xml
- Use `getUserWithID` method instead of `getUserListWithID` method to fetch the user in `scim2/Me` delete endpoint.
- Improved `getUserWithID` method (https://github.com/wso2/carbon-kernel/pull/3559) will fetch the user using the userstore domain instead of iterating through all userstores.
- Fixes - https://github.com/wso2/product-is/issues/15656
=> Fix scim2/me delete issue

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java, pom.xml
Only the tenant owner is allowed to remove users from the Administrator role. Framework throws an error if the authorized user doesn't have the permissions when making the request. Previously a 500 error was thrown in this scenario. However 403 should be returned instead of 500.
- This PR should be merged first https://github.com/wso2/charon/pull/386
=> Handle forbidden responses when updating roles with a patch request

.github/workflows/pr-builder.yml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
This PR aims to address the issues mentioned in https://github.com/wso2/product-is/issues/16097.
The goals of this PR are to:
- Change the error responses when adding a member to a group with invalid display name.
- Change the error responses when adding a member to a group with invalid id.
- Change the error responses when a user is added with mismatching id and display name.
- Change the error response when removing a non-existent user from a group
- Fix the issue of receiving a 400 error when attempting to `remove and add a user` scenario by using the user ID. However, this was working with the user display name.
=> Fix Getting 500 error response for client errors in SCIM/Groups PATCH

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/SchemaResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/util/SupportUtils.java
Related issue:
- https://github.com/wso2/product-is/issues/16906
Improve resolving tenant domain when tenant qualified URL feature is enabled. If the tenant domain is available in the context retrieve it otherwise retrieve tenant domain from the privileged carbon context.
=> Improve tenant qualified URL feature.

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java, pom.xml
To provide bulk user import feature for sub organizations the `scim2/Bulk` endpoint should be accessible for sub-organizations, which allows various operations, including role creation.
However, the initial intent was to avoid supporting the /scim2/Roles endpoint in the o/<org-id> path for sub-organizations. Instead, the organization roles should be used to manage permissions.
This PR introduces a restriction that prevents role creation from sub-organizations.
=> Block role creation for sub organizations.

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, pom.xml
Issue: https://github.com/wso2/product-is/issues/16379
Related PRs: 
https://github.com/wso2/identity-organization-management-core/pull/95
https://github.com/wso2-extensions/identity-organization-management/pull/261
=> Handle email domain validation failures for org discovery

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
$Subject
Part of https://github.com/wso2/product-is/issues/16363
=> Return 400 BadRequest for pre check validation failure of role deletion

components/org.wso2.carbon.identity.scim2.provider/src/main/webapp/WEB-INF/cxf-servlet.xml
$subject
The organization perspective APIs were referenced by the existing organization allowed APIs
=> Add org perspective SCIM2 servlet mappings

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
=> Fixed empty permission list replace issue in v2 Role patch

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandler.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponent.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponentHolder.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtil.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtilTest.java
Previously, the mandatory id attribute of admin role was update using a random UUID. However, in the current role v2 implementation, we set the UUID from the kernel to the UM_HYBRID_ROLE table. Instead of updating the ID attribute of the role with a random UUID, we set the role id attribute by retrieving the UUID from the UM_HYBRID_ROLE table.
=> Fix admin role mandatory attribute update

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponent.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, pom.xml
When trying to access scim2/v2/Roles endpoint for system role, getting 404 error.
```
{
"schemas": [
],
"detail": "Role id: c65e5d2a-f65a-4ed6-a2b6-cacaa34fbced does not exist in the tenant: carbon.super",
"status": "404"
}
```
This is due to not updating scim attribute metadata for system role in super tenant. With this fix, system role metadata is updated when activating the SCIMCommonComponent.
Issue - https://github.com/wso2/product-is/issues/17350
=> Fix error while retrieving system role in super tenant

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
Internal/everyone role's and Internal/system role's SCIM properties should be added only if they are not in the table during server startup
Fix for https://github.com/wso2/product-is/issues/17443
=> Fix error log on pack restart

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
This PR adds the managedOrg attribute to `scim2-schema-extension.config` file. This will return the organization id which manages the invited users in `GET /t/<tenant_name>/o/scim2/Users` response.
- https://github.com/wso2/product-is/issues/17492
=> Add managedOrg attribute

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponent.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponentHolder.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, pom.xml
This PR adds the support for federated IDP groups to role assignments.
Related issue - https://github.com/wso2/product-is/issues/17429
Need to merged after - https://github.com/wso2/carbon-identity-framework/pull/5143
=> Add support for federated IDP groups to role assignments

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
In the new authz runtime, when retrieving the roles of a group, the audience for roles with similar names is the same.
- https://github.com/wso2/product-is/issues/17652
=> Fix group's list of roles audience issue

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
In the new authz runtime, when retrieving the roles of a user, the audience for roles with similar names is the same. This PR fix this issue
- https://github.com/wso2/product-is/issues/17909
- https://github.com/wso2/carbon-identity-framework/pull/5186
=> Fix user's list of roles audience issue

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
**Purpose**
Fix internal server errors when updating an application role with a permission that is not authorized for the application.
**Related Issue**
- https://github.com/wso2/product-is/issues/18183
=> Fix internal server errors when updating an application role.

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/RoleResourceV2.java, pom.xml, scim2.yaml
**Purpose**
Support attributes and excludeAttributes query params for List roles v2 endpoint
**Related Issues**
https://github.com/wso2/product-is/issues/18096
=> Support attributes and excludeAttributes query params for List roles v2 endpoint

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
- Introduce a new identity claim `preferredMFAOption` for  user preferred MFA login feature.
- https://github.com/wso2/product-is/issues/18857
=> Introduce a new claim `preferredMFAOption` to scim2 extension schema

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtil.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
With this update superAdmin related patch and delete scim operations will only be allowed to be performed by the superAdmin themselves.
=> Add superAdmin validation for patch and delete operations

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
Adding the correct scimType values mentioned in the RFC https://datatracker.ietf.org/doc/html/rfc7644#section-3.12 to BadRequestException
Related issue https://github.com/wso2/product-is/issues/19072
=> Add correct scimType values to BadRequestException

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
Fixes https://github.com/wso2/product-is/issues/19092
The following response will be given now for the PATCH /scim2/v2/Roles/invalidRole request
```
{
"schemas": [
],
"detail": "A role doesn't exist with id: invalidRole in the tenantDomain: carbon.super",
"status": "404"
}
```
=> Return 404 response when changing a non-existing role

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/GroupDAO.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMGroupResolver.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java, pom.xml
Implement Group UUID support for ReadWrite LDAP and AD. 
- Resolves 2nd Todo in https://github.com/wso2/product-is/issues/7913
- Resolves https://github.com/wso2/product-is/issues/7915
- Part of https://github.com/wso2/product-is/issues/16368
- Use the UM APIs and improve the SCIM implementation.
- Improve the listeners in SCIM to read meta attributes from user core events
- https://github.com/wso2/carbon-kernel/pull/3812 has to be merged and a new kernel version to be released.
- Use the new kernel version in product-is and bump in this repo.
=> Provide Group UUID support for write operations

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtil.java
When the initial organization is loaded, we create admin groups and add attributes by calling SCIM listeners. This is not required if group uuid is enabled for the userstore. Therefore, the fix is to skip SCIM update if the user store has the group uuid support.
=> Fix SCIM table update for group uuid enabled user store

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java
Fix the following invalid warn log being printed in the console when updating a group name of the group uuid enabled userstore.
```
"Non-existent group: " + oldRoleName + " is trying to be updated.."
```
=> Fix invalid warn log being printed in the console

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
$subject
- https://github.com/wso2/product-is/issues/19485
=> Throw BadRequestException instead of server error for  SCIM2 users & groups filtering with invalid filter operation

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolver.java
- Fixes: https://github.com/wso2/product-is/issues/19845
Add the new error code to the error resolver.
=> Fix the invalid http error code for existing group name

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponent.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponentHolder.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/Scenarios.java, pom.xml
Add a new event to track credential updates happening through SCIM.
https://github.com/wso2-enterprise/iam-engineering/issues/963
Merge after merging https://github.com/wso2/carbon-identity-framework/pull/5564
=> Add new event to track SCIM credential updates

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandler.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandlerTest.java
Previously, when addressing https://github.com/wso2/product-is/issues/14095, the updateRoleName method's was changed to print a warn log instead of throwing an exception via https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/435, which was a temporary fix which had not been reverted even after a proper fix was added.
This PR reverts the temporary fix and allows an exception to be thrown instead of a warn log.
With this change, the SOAP API will be able to identify the failure of the operation and return the status as 500 Internal Server Error along with the error message.
- https://github.com/wso2-extensions/identity-user-ws/pull/64
- https://github.com/wso2/product-is/issues/19114
=> Fix lack of exception when attempting to update a non-existent role name

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
- Return the user id from the carbon context if that exists. Otherwise the existing implementation will follow.
=> Fix user deletion issue in the sub organizations

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java, pom.xml
This PR will fix the `default maximum number of records per request`(100) is not being honored by SCIM GET Users API. As the fix, added a validation for the count parameter which check whether the count is exceeding the configured `default maximum number of records per request` parameter. If yes, then sets the count value to 100.
1. Merge and Release https://github.com/wso2/carbon-identity-framework/pull/5599 PR.
2. Bump framework version with the released version.
3. Run the PR builder.
Related issues:
- https://github.com/wso2/product-is/issues/20030
=> Add validation for the count parameter

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
- Avoid to log the PII data when there is a bad request error.
- Masking the data from the error log.
=> Masking data from the error log when Bad request

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
- Skipping the super admin check if the request initiated from a sub organization.
=> Improve user delete and update for sub organizations

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
In SCIM2 Roles V2 api, patch operation will fail when trying to remove a user from a role if the request only contains the `display` property of the user. This PR fixes this issue
=> Resolve user ID from username when user ID is not provided

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
> Mask sensitive information and prevent them from being logged.
=> Mask sensitive information in logs

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
> Currently we do not have an empty check before updating IDP groups during role creation. Due to this IDP group update event is triggered unnecessarily. This PR add an additional empty check before updating IDP groups
=> Add empty check before updating IDP groups

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, pom.xml
$subject
- https://github.com/wso2/carbon-kernel/pull/3997
=> Fix unique key violation exception when concurrent group patch requests trying to add same users to the group

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2Test.java, components/org.wso2.carbon.identity.scim2.common/src/test/resources/testng.xml
Fix SCIM error handling to provide appropriate messages when a group display name is used instead of a group ID.
To ensure compliance with RFC 7644 and provide clear, actionable error messages to users when an invalid request is made with a group display name.
- Implemented error response with `scimType` set to `invalidSyntax` for requests using a group display name instead of a group ID.
- Provided a clear and concise error message in the `detail` field.
- Handled the fix for both V1 and V2 roles.
- Ensured the error response adhered to the SCIM specification.
Resolves [#20334](https://github.com/wso2/product-is/issues/20334)
=> Fix: SCIM error message for invalid request values in V1 and V2 Roles Remove-Add-Replace operations (fixes #20334)

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
Issue: https://github.com/wso2/product-is/issues/20496
When count(limit) > 0, use the `getMultiAttributeFilteredUsersWithMaxLimit` with limit is provided as the given count given. 
Adiition to that this contain the fix to honor the provided count value in the SCIM2 request for multi attribute filtering flow.
Ported the logic(used in the single attribute filtering flow) with minor modification: https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L1885-L1914
=> Fix multi-attribute user filter with count provided.

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
- To add a max limit to the `https://api.asgardeo.io/t/{organization-name}/scim2/Users/.search` api
- The same thing is done to the getUser api by https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/541
- From this PR, this logic is moved to a common place which cover both below APIs.
-  `/scim2/Users/.search` --> POST 
- /scim2/Users' --> GET
=> Refactor the users list limit to a common method

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java
Reverts wso2-extensions/identity-inbound-provisioning-scim2#560
- This affects both /scim2/Users GET api and /scim2/Users/.search API and can be a behavioural change for either one, need to revisit the solution
=> Revert "Refactor the users list limit to a common method"

features/org.wso2.carbon.identity.scim2.common.feature/resources/org.wso2.carbon.identity.scim2.common.feature.default.json
To update the SCIM2 `documentation_uri` in the `/ServiceProviderConfig` endpoint response.
Updating the `documentation_uri` to https://is.docs.wso2.com/en/latest/apis/scim2-users-rest-apis/ to ensure compatibility with future releases. The new URL does not include specific release versions, allowing it to rely on the latest updates.
Resolves [#20738](https://github.com/wso2/product-is/issues/20738)
=> Update scim2 documentation_uri

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandlerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolverTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentityResourceURLBuilderTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2Test.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListenerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/test/utils/CommonTestUtils.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtilTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtilTestForGroup.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapperTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AuthenticationSchemaTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMConfigProcessorTest.java, pom.xml
- Remove the usage of the powermock library from the test cases.
- Powermock library is becoming dead and it is so far has not supported Java 21. With our effort to provide support Identity Server product compiling with Java 21, this becomes a blocker.
=> Remove powermock usage from unit tests

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/DefaultSCIMUserStoreErrorResolverTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentityResourceURLBuilderTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/IdentitySCIMManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2Test.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListenerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtilTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AdminAttributeUtilTestForGroup.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java, pom.xml
- Remove the usage of the powermock library from the test cases.
- Powermock library is becoming dead and it is so far has not supported Java 21. With our effort to provide support Identity Server product compiling with Java 21, this becomes a blocker.
=> Remove powermock usage

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
####
- https://github.com/wso2/product-is/issues/21410
=> Filter users by group filter failure after max user count improvement

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, pom.xml
Add ExcludedUserStoreDomains claim property to schemas.
- https://github.com/wso2-enterprise/asgardeo-product/issues/22601
- https://github.com/wso2/carbon-identity-framework/pull/6096
- https://github.com/wso2/carbon-kernel/pull/4110
- https://github.com/wso2-extensions/identity-governance/pull/872
=> Add ExcludedUserStoreDomains Property to schema

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponent.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/SCIMCommonComponentHolder.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java, pom.xml
- $subject
- Read the tenant wise configuration to set the hard limit for scm2/Users/.search API response
- https://github.com/wso2/carbon-identity-framework/pull/5839
=> Add hard limit for scim2/Users/.search API response

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java
Return error code 20035 formatted with the error message for a password policy violation error thrown by PolicyViolationException with the same error code.
- https://github.com/wso2/product-is/issues/21421
=> Return error code for pwd policy violation

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java, pom.xml
- $subject
- Allow to create, update and delete the roles in the sub organization level.
- Restricting the shared role permission update and delete shared roles in the sub organization level.
- Related to https://github.com/wso2/product-is/issues/21208
- Update the framework version after merging the following framework PRs.
- https://github.com/wso2/carbon-identity-framework/pull/6002
- https://github.com/wso2/carbon-identity-framework/pull/6010
=> Enable role management in organization level

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2Test.java, pom.xml
- $subject
- Part of the fix for https://github.com/wso2/product-is/issues/21208
=> Add role properties to the SCIM2 Role response

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
The PRIMARY domain has to be appended when filtering the groups by name. If domain is not specified, all the groups from all the user stores will be listed where the filtering condition is matched.
Here is a similar place[1] where same logic is followed, where domain is appended to the group(role) name instead of using the `UserCoreUtil.addDomainToName` method which skip adding "PRIMARY" domain for the groups. 
[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L2091~L2098
- https://github.com/wso2/product-is/issues/22189
=> Improve domain qualified username handling when filter users by group with PRIMARY domain

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, pom.xml
$Subject when there is a value for SharedProfileValueResolvingMethod claim property/ resolved by the system.
eg:
```
[
{
"name": "Core",
"description": "Core",
"attributes": [],
"id": "urn:ietf:params:scim:schemas:core:2.0"
},
{
"name": "User",
"description": "User Account",
"attributes": [
{
"uniqueness": "NONE",
"displayName": "URL",
"name": "profileUrl",
"displayOrder": "10",
"description": "URL",
"mutability": "READ_WRITE",
"type": "STRING",
"multiValued": false,
"caseExact": false,
"returned": "DEFAULT",
"required": false,
"sharedProfileValueResolvingMethod": "FromOrigin"
},
{
"displayName": "Email",
"displayOrder": "6",
"description": "Email Address",
"type": "COMPLEX",
"required": true,
"subAttributes": [],
"regEx": "^([a-zA-Z0-9!#$'\\+=^_\\.{|}~\\-&])+\\@(([a-zA-Z0-9\\-])+\\.)+([a- …
```
=> Return SharedProfileValueResolvingMethod property value for each claim in /scim2/Schemas API 

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2Test.java
When performing an ADD operation on a role's permissions via the SCIM2 API, the existing permissions are incorrectly replaced instead of appending the new permissions.
The issue was caused by the `prepareReplacedPermissionLists` method being executed for every patch operation. This method clears the existing permissions, which is appropriate for the REPLACE operation but not for ADD or REMOVE.
- The fix ensures that `prepareReplacedPermissionLists` is only executed for the REPLACE operation, preventing unintended clearing of permissions during ADD or REMOVE operations.
- Added unit tests scenarios to cover the permission update operations
https://github.com/wso2/product-is/issues/21628
=> Fix ADD operation replacing permissions of the role

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, pom.xml
- Add attribute profiles related properties as JSON object to scim2/Schemas response.
- Introduce the global supportedByDefault property. Previously, only attributes marked as supportedByDefault were returned in the response. Now, any profiles with supportedByDefault set to true will also be included.
- https://github.com/wso2/product-is/issues/22163
- https://github.com/wso2/charon/pull/420
=> Add attribute profiles properties to schema response.

components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/MeResource.java, components/org.wso2.carbon.identity.scim2.provider/src/main/java/org/wso2/carbon/identity/scim2/provider/resources/UserResource.java, pom.xml
> $Subject
- https://github.com/wso2/product-is/issues/22351
=> Populate Identity Context in password update flow

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
$Subject
Fix: https://github.com/wso2/product-is/issues/22473
Cause: https://github.com/wso2/product-is/issues/22473#issuecomment-2614560374
=> Update claim change when old claims don't have value and updated claim set has empty value

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapper.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/AttributeMapperTest.java
This PR fixes an issue where :attributeName was being removed from all occurrences within the SCIM attribute URIs instead of only the last occurrence. The fix ensures that only the last occurrence of the suffix.
- https://github.com/wso2/product-is/issues/22699
=> Fix incorrect attribute name removal in SCIM URIs

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/GroupDAO.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/SQLQueries.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/group/SCIMGroupHandler.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListenerTest.java
$subject
This adds the fix introduced in https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/590 to the **doPostUpdateRoleName** listener in SCIMUserOperationListener.
When a group is modified by renaming its display name, the group's last modified date needs to be updated. This PR fixes that issue by updating the group's last modified date on such scenarios.
**Note**: The SCIM level update is only required when the group unique id feature is disabled. Otherwise, the attributes will be stored in the user store.
https://github.com/wso2/product-is/issues/19244
=> Set the last update date in the post-update role name listener

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
- https://github.com/wso2/product-is/issues/22570
When max user list length is set as smaller value, the issue can be easily reproduced.
```
[user_store.properties]
MaxUserNameListLength=3
```
The following flows are fixed in this PR.
1. Filter users without domain. 
2. Filter users with domain
with count param and without count param.
=> Fix user filtering when max user list length exceeds results exist

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
- $subject
- Part of the fix for : https://github.com/wso2/product-is/issues/22544
- When creating the roles from the sub organization, those roles only needs to be assigned only to the applications which are created directly in the sub organization.
- This fix will check the type of the application and if it is not a shared / fragment application in the sub organization level, then that application will be available to the role assignment / creation.
=> Restrict roles created in sub orgs to be associated with the non-shared apps in the sub organization

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
Extend the SCIM2 schema to support the new shared type attribute and return it as part of the user response.
- Introduce `sharedType` as a standalone SCIM2 attribute.
- Add `sharedType` as a sub-attribute under `urn:scim:wso2:schema`.
- Ensure the attribute follows SCIM2 standards (read-only, default returned, etc.).
- Defined a new SCIM2 attribute with `attributeURI: urn:scim:wso2:schema:sharedType`.
- Set `mutability` to `readOnly`, `returned` to `default`, and `dataType` to `string`.
- Added `sharedType` to the `subAttributes` list of `urn:scim:wso2:schema`.
Merge after: [[Claim][IS] Add Shared Type Local Claim and Map to SCIM2 Claim #6511](https://github.com/wso2/carbon-identity-framework/pull/6511)
Merge before: [[Claim] Return Shared Type Claim in User Profile Responses …
=> [Claim][IS] Update SCIM2 Schema to Include Shared Type Attribute

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/cache/SCIMSystemAttributeSchemaCache.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/cache/SCIMSystemAttributeSchemaCacheEntry.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/cache/SCIMSystemAttributeSchemaCacheKey.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/handlers/SCIMClaimOperationEventHandler.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCustomSchemaProcessor.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/cache/SCIMSystemAttributeSchemaCacheTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/handlers/SCIMClaimOperationEventHandlerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/resources/testng.xml
This PR introduces a caching mechanism for SCIM system attribute schemas to improve performance and reduce redundant processing. The `SCIMSystemAttributeSchemaCache` is implemented to store system attribute schemas per tenant, along with corresponding cache entry and key classes for efficient management. The caching logic is integrated into `SCIMUserManager` and `SCIMCommonUtils` to optimize schema retrieval, while `SCIMClaimOperationEventHandler` has been updated to clear the cache when relevant claims are modified.
- https://github.com/wso2/product-is/issues/23104
=> Add cache for system attribute schema

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, pom.xml
- Failures from Pre Update Password Action returns to scim level as UserStoreClientExceptions. 
- Since those failures comes with a respective error code, we can directly handle them using that.
- Hence added a method to handle the failures from the Pre Update Password action
Scim2/users update:
```
{
"schemas": [
],
"detail": "Compromized Password. Provided Password has been compromized",
"status": "400"
}
```
Scim2/me update:
```
{
"schemas": [
],
"scimType": "invalidValue",
"detail": "Error while updating attributes of user. Compromized Password. Provided Password has been compromized",
"status": "400"
}
```
New API responses:
Scim2/users update:
```
{
"schemas": [ …
```
=> Handle failures from Pre Update Password action

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/handlers/SCIMClaimOperationEventHandler.java, pom.xml
This PR introduces a validation mechanism to block the addition of custom claims to spec-defined and system SCIM schemas, ensuring compliance with SCIM standards and preventing potential conflicts.
- https://github.com/wso2/product-is/issues/23162
=> Block adding custom claims to spec-defined and system schema

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
$subject
- https://github.com/wso2/product-is/issues/23376
- https://github.com/wso2/product-is/issues/23378
=> Improve pagination for scim2/groups API

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java
Issue:
- https://github.com/wso2/product-is/issues/23568
With this PR, the `failureReason` and `failureDescription` from the external authentication service response are correctly mapped to `scimType` and `detail`, respectively, ensuring proper error representation in the SCIM error response.
The current response received for the password update request is:  
```json
{
"schemas": [
],
"scimType": "invalidValue",
"detail": "The provided password is compromised. Provide something different.",
"status": "400"
}
```
However, to ensure proper error representation, the response should follow this format:  
```json
{
"schemas": [
],
"scimType": "Compromised password",
"detail": "The provided password is …
```
=> Map failure message and description from pre update password extension to scimType and detail

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/action/PreUpdateProfileActionExecutor.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/internal/action/PreUpdateProfileActionExecutorTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/test/constants/TestConstants.java, pom.xml
This PR updates the pre executable validations for the PRE PROFILE UPDATE ACTION execution consuming the flowInitiator claim property of the particular local claim. 
The particular local claims which is getting updated or deleted will be retrieved from the claim metadata service and check whether it is a flowInitiator typed claim.
Further this updates the relevant unit tests written for updating flowInitiator typed claims.
Merge after https://github.com/wso2/carbon-identity-framework/pull/6688
- https://github.com/wso2/product-is/issues/23838
=> Exclude flowInitiator claims

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
To improve traceability of user attribute updates in the `SCIMUserManager` class by adding targeted debug logs for key operations, reducing the need for manual log patches.
* Provide clearer context for user attribute updates.
* Improve traceability of user existence checks.
* Capture potential configuration issues in SCIM to Local claim mappings.
* Minimize unnecessary log clutter by focusing on critical checkpoints.
* **User Existence Check:** Added a debug log to indicate the result of the user existence check.
* **Password Update Block:** Logged password update attempts without revealing sensitive information.
* **Claim Mapping Check:** Added a log to indicate if the SCIM to Local claim mapping list is unexpectedly empty.
public issue: https://github.com/wso2/product-is/issues/23923 …
=> Add targeted debug logs for user attribute updates in SCIMUserManager

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
This PR improves the SCIM user‐creation flow to show a clear error whenever the configured password-pattern regex is malformed. Instead of continuing silently or returning `202 Accepted`, `500 Internal Server Error` with a detailed error message is thrown as soon as the loading password policies error code is encountered.
```
{
"schemas": [
],
"detail": "Error occurred while loading Password Policies: the configured password-pattern regex is invalid. Please verify and correct your regex syntax.",
"status": "500"
}
```
- https://github.com/wso2/product-is/issues/23943
- https://github.com/wso2-extensions/identity-governance/pull/955
=> Improve error handling of password policy validation in SCIM User Manager

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, pom.xml
- https://github.com/wso2/product-is/issues/24049
- https://github.com/wso2/charon/pull/433
- https://github.com/wso2/carbon-identity-framework/pull/6753
```
{
"displayName": "Account Type",
"displayOrder": "20",
"profiles": {
"console": {
"supportedByDefault": true
}
},
"sharedProfileValueResolvingMethod": "FromOrigin",
"type": "STRING",
"required": false,
"uniqueness": "NONE",
"name": "account_type",
"canonicalValues": [
{
"value": "SVA",
"displayValue": "SAVINGS Account"
},
{
"value": "CA",
"displayValue": "CURRENT Account"
},
{
"value": "FD",
"displayValue": "FIXED Deposit"
}
],
"supportedByDefault": "false",
"mutability": "READ_WRITE",
"multiValued": false,
"caseExact": false,
"returned": "DEFAULT"
}
```
=> Support canonical values for SCIM schema response

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, pom.xml
- $Subject
- With this PR Ne filering operation is supported only for the user's filtering(`scim2/Users`), for the group's filtering (`scim2/Groups`) a `400 Bad Request` response is returned.
- https://github.com/wso2/carbon-kernel/pull/4305
- https://github.com/wso2-extensions/identity-governance/pull/957
=> Support ne operation for user's filtering

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, pom.xml
> $subject
- https://github.com/wso2/product-is/issues/24392
The SCIM2 schemas response will have the input formats as shown below.
=> Expose input formats from SCIM schemas response

features/org.wso2.carbon.identity.scim2.common.feature/resources/scim2-schema-extension.config
`managedOrg` attribute in `urn:scim:wso2:schema` is used to denote the organization id where the user is managed.
This value will be populated in the shared and invited users to identify their managed organization from the sub org level.
Since this attribute is managed internally, it shouldn't get updated. 
Eventhough currently the attribute modification is validated at the user core level, we need to enforce the validation from the scim level as well.
So this PR will update the scim2-extension-schema.config file to make the mutability of this claim to be `readOnly`
So with this error message shown after trying to update the claim value will be changed as follows,
Previous error
```
{
"schemas": [
],
"detail": "The managed organization is a …
```
=> Changed managedOrg claim to a readonly claim

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/action/PreUpdateProfileActionExecutor.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/internal/action/PreUpdateProfileActionExecutorTest.java, pom.xml
- Refactor PreUpdateProfileActionExecuter to utillize the new  getMinimalOrganization(String orgId, String tenantDomain) method from Organization Manager to resolve user organization.
- https://github.com/wso2/identity-organization-management-core/pull/194
- https://github.com/wso2/product-is/issues/24855
=> Refactor organization resolving logic in PreUpdateProfileAction Executer with the new getMinimalOrganization() in org manager

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/action/PreUpdateProfileActionExecutor.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/component/SCIMCommonComponent.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/internal/component/SCIMCommonComponentHolder.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/internal/action/PreUpdateProfileActionExecutorTest.java, pom.xml
> 
- https://github.com/wso2/carbon-identity-framework/pull/7070
- https://github.com/wso2/carbon-identity-framework/pull/7072
- https://github.com/wso2/product-is/issues/24959
=> Fix Resolving user id in PreUpdateProfileActionExecutor when shared user profile is updated

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
> With new role v3 implementation it looks it has missed / removed to have the error handling for the workflow engaged during role creation.
- https://github.com/wso2/product-is/issues/23374
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/658
=> Handle workflow engagement during role creation for the role-v3 API

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
> Related Issue: https://github.com/wso2/product-is/issues/25067
This pull request introduces a change to the error handling logic in the `createUser` method of `SCIMUserManager.java`. The update improves how client exceptions are processed when user creation fails.
- Ensure SCIM API failure responses clearly represent the cause of the error.
- Remove redundant details such as masked usernames from failure messages when unnecessary.
- Added a call to `handleAndThrowClientExceptionForActionFailure(e)` in the `UserStoreClientException` catch block.
- Verified that responses now have the following improved format:
**Previous response format:**
```json
{
"schemas": [
],
"scimType": "invalidValue",
"detail": "Error in adding the user: …
```
=> Fix incorrect SCIM failure response in Pre Update Password Action

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java
> Resolves https://github.com/wso2/product-is/issues/24574
> When `consider_total_records_for_total_results_of_ldap = true`, it should only be applicable for LDAP userstores. If there are JDBC user stores, we can use the optimal approach to achieve better performance.
=> Improve performance when calculating total user count in JDBC user stores

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
Currently, for user role assignment related workflow errors, scimType and description of the returned error are incorrect. This PR addresses this by assigning `invalidValue` as the scimType with appropriate error description.
Related Issue: 
- https://github.com/wso2/product-is/issues/25251
=> Fix scimType and description for role workflow errors

components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManagerV2.java
Currently, for user role assignment related workflow errors, scimType and description of the returned error are incorrect. This PR addresses this by assigning `invalidValue` as the scimType with appropriate error description.
Related Issue: 
- https://github.com/wso2/product-is/issues/25251
=> [Next Branch] Fix scimType and description for role workflow errors 

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java, pom.xml, scim2.yaml
- According to the [SCIM 2.0 specification](https://datatracker.ietf.org/doc/html/rfc7644#section-3.12:~:text=If%20the%20service,Section%203.12.), a 409 Conflict response should be returned when a uniqueness constraint is violated. This PR introduces configurable error handling for duplicate claims in SCIM2 user management by adding a new configuration property (Property is retrieved from the config store, if not found fall back to the server level config) that allows SCIM2 endpoints to return a 409 Conflict instead of the current default 400 Bad Request when such violations occur.
- To enable the corresponding configuration, execute the following curl :
```
curl --location 'https://<HOSTNAME>/t/<ORG>/api/identity/config-mgt/v1.0/resource/compatibility-settings' \
--header 'Authorization: …
```
=> [NEXT] Support returning 409 Conflict for duplicate claims in SCIM2 user management

components/org.wso2.carbon.identity.scim2.common/pom.xml, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonConstants.java, components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtils.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManagerTest.java, components/org.wso2.carbon.identity.scim2.common/src/test/java/org/wso2/carbon/identity/scim2/common/utils/SCIMCommonUtilsTest.java, pom.xml, scim2.yaml
- According to the [SCIM 2.0 specification](https://datatracker.ietf.org/doc/html/rfc7644#section-3.12:~:text=If%20the%20service,Section%203.12.), a 409 Conflict response should be returned when a uniqueness constraint is violated. This PR introduces configurable error handling for duplicate claims in SCIM2 user management by adding a new server level configuration  that allows SCIM2 endpoints to return a 409 Conflict instead of the current default 400 Bad Request when such violations occur.
> Note : While Identity Server only needs a server-level configuration, the logic for `isReturnConflictOnClaimUniquenessViolationEnabled()` is intentionally aligned with the NEXT branch [[1]](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/719)[ …
=> Support returning 409 Conflict for duplicate claims in SCIM2 user management
